### ISSUE TITLE
Like typical Linux commands

### ISSUE THREAD

**Issue by v8yte** [Jumpaku/cyamli#31]
Like typical Linux commands, there are times when a main command with options is sufficient, without the need for a subcommand.
I think it would be better if the subcommand were not mandatory, as shown below. What do you think?
```
<program> [<subcommand>] [<option>|<argument>]... [-- [<argument>]...]
```

**Comment by Jumpaku** [comment]
Thank you for your question!

You say that cyamli should handle command line arguments without subcommands.
However, I think that cyamli can those command line arguments, and changes are not needed.

This is because the README says that: 

> `<subcommand>` is a sequence of tokens ...
> `<subcommand>` **may be empty**, which means the execution of the root command.

**Comment by Jumpaku** [comment]
The root command can have an option and a positional argument using the following yaml.

```yaml
name: curl
options:
  -header:
    short: -h
arguments:
  - name: url
```

This schema enables to execute program with command line arguments `curl -header="Host: xxxxx" localhost`.


Note that you cannot use the option `-H` because the pattern `^[a-z][a-z0-9]*$` does not allow upper case characters for option name. Please use `-h` or `-header` instead.
Also you cannot use the option name and value `-header "Host: xxxxx"` because the pattern `<option_name>[=<option_value>]` does not allow option values separated from option names. Please use `-header="Host: xxxxx"` instead.
These limitation is to simplify implementation and generated code.

**Comment by v8yte** [comment]
thx! I have confirmed that it works without issues on my local program as well.

> ❯ go run main.go cli.gen.go -t
> {} value is not specified to option "-t"
> demo
> 
> demo
> 
>     Description:
>         demo app to get table information from databases
> 
>     Syntax:
>         $ demo  [<option>]...
> 
>     Options:
>         -test=<string>, -t=<string>  (default=""):
>             test
> 
>     Subcommands:
>         fetch:
>             show information of tables
> 
>         list:
>             list tables
